### ISSUE TITLE
error when importing library

### ISSUE THREAD

**Issue by ckaros** [raycewest/pykeeb#5] opened 2018-01-24 15:43 UTC
I appears keyswitch_mount.py is trying to import switch and keycap stl files with an Import function that is not defined. 

```python
NameError                                 Traceback (most recent call last)
<ipython-input-2-11b30d5ff71e> in <module>()
      1 import openpyscad as o
----> 2 import pykeeb as k

C:\CKAROS_PROJECTS\minicoda3_64\envs\keeb\lib\site-packages\pykeeb\__init__.py in <module>()
      1 from .pykeeb import *
----> 2 from .keyswitch_mount import Keyswitch_mount
      3 from .keyboard_matrix import Keyboard_matrix
      4 from .keyboard_arc import Keyboard_arc

C:\CKAROS_PROJECTS\minicoda3_64\envs\keeb\lib\site-packages\pykeeb\keyswitch_mount.py in <module>()
      2 from .pykeeb import *
      3 
----> 4 class Keyswitch_mount:
      5         #width is X, length is Y
      6         thickness = 3

C:\CKAROS_PROJECTS\minicoda3_64\envs\keeb\lib\site-packages\pykeeb\keyswitch_mount.py in Keyswitch_mount()
      5         #width is X, length is Y
      6         thickness = 3
----> 7         alps_keyswitch = Import('/usr/models/matias.stl').color('Gray')
      8         mx_keyswitch = Import('/usr/models/cherry.stl').color('Gray')
      9         dsa_key = Import('/usr/models/dsa_1u.stl').color('White') #18x18x8mm

NameError: name 'Import' is not defined

```

**Comment by r4dr3fr4d** [comment] 2018-01-24 23:19
Can't reproduce that by just typing your import-as statements.  "Import" is an openpyscad function.  Can you give me any other info?

**Comment by ckaros** [comment] 2018-01-24 23:57
is Import a function in the current openpyscad lib? I can't find it here:

https://github.com/taxpon/openpyscad

**Comment by ckaros** [comment] 2018-01-25 00:37
can you post the versions of the libs you're using? Just want to make sure I am setting up the environment correctly. I am using pip to install both openpyscad and pykeeb.

I commented out the code in keyswitch_mount.py the require the stl files (the 3 import lines and the get_keyswitch function) and attempted to run your pyergo60.py script and got the following error:


```python

C:\Users\Dean\Downloads\pyergo60-master\pyergo60-master> python .\pyergo60.py
Traceback (most recent call last):
  File ".\pyergo60.py", line 7, in <module>
    plate = Keyboard_matrix(rows, columns, 1.5, .5, 3, [0,0,12], 0, 5)
  File "C:\Users\Dean\miniconda\lib\site-packages\pykeeb\keyboard_matrix.py", line 36, in __init__
    self.generate()
  File "C:\Users\Dean\miniconda\lib\site-packages\pykeeb\keyboard_matrix.py", line 46, in generate
    self.row_hulls = [[(self.sm[row][column].get_front(self.row_hull_thickness, self.row_hull_extrude) + self.sm[row+1][column].get_back(self.row_hull_thickness, self.row_hull_extrude)).hull() for column in range(self.columns)] for row in range(self.rows-1)]
  File "C:\Users\Dean\miniconda\lib\site-packages\pykeeb\keyboard_matrix.py", line 46, in <listcomp>
    self.row_hulls = [[(self.sm[row][column].get_front(self.row_hull_thickness, self.row_hull_extrude) + self.sm[row+1][column].get_back(self.row_hull_thickness, self.row_hull_extrude)).hull() for column in range(self.columns)] for row in range(self.rows-1)]
  File "C:\Users\Dean\miniconda\lib\site-packages\pykeeb\keyboard_matrix.py", line 46, in <listcomp>
    self.row_hulls = [[(self.sm[row][column].get_front(self.row_hull_thickness, self.row_hull_extrude) + self.sm[row+1][column].get_back(self.row_hull_thickness, self.row_hull_extrude)).hull() for column in range(self.columns)] for row in range(self.rows-1)]
AttributeError: 'Union' object has no attribute 'hull'
```

**Comment by r4dr3fr4d** [comment] 2018-01-25 01:15
Okay yeah reinstalling openpyscad via pip gave me the same result after retrying it.  He must've updated it without updating his github repo

**Comment by r4dr3fr4d** [comment] 2018-01-25 01:15
I'll have to investigate further and see what's up.

**Comment by r4dr3fr4d** [comment] 2018-01-25 02:11
It was actually the opposite - the github repo had a PR with the Import function merged, but PyPI wasn't updated.  Go to [openpyscad](https://github.com/taxpon/openpyscad) download as a tar.gz, then ```# pip install openpyscad-master.tar.gz```.  Then it should work.

**Closed as completed by r4dr3fr4d** 2018-01-25 02:11 UTC
